#!/bin/bash

# usage:
# code-edit <slug>

set -o errexit

[[ -z $1 ]] && { echo error; exit 1; }

slug=$1
org=$(  echo $slug | cut -d'/' -f1 )
repo=$( echo $slug | cut -d'/' -f2 )
[[ $slug == */* ]] || org=$GITHUB_USERNAME
slug=$org/$repo

[[ -d ~/desktop/code/$slug ]] || { echo error; exit 1; }

cd ~/desktop/code/$slug

[[ -f ./script/start ]] || code . --reuse-window && ./script/start

exit
