#!/bin/bash

# usage:
# bitbucket_create_repo <slug>

set -o errexit

source ~/desktop/system/script/source/common.sh

assert-os
assert-python
assert-python-package requests

[[ -z $BITBUCKET_USERNAME ]] && { echo "error: missing BITBUCKET_USERNAME environment variable"; exit 1; }

token_path=~/desktop/system/key/token-bb

[[ -f $token_path ]] || { echo "error: missing token file"; exit 1; }

# shellcheck disable=SC2155
export BITBUCKET_TOKEN=$( cat $token_path )

python ~/desktop/system/script/source/forge_create_repo_bb.py $1
