#!/bin/bash

set -o errexit

ln --force ~/desktop/system/profile/belimoth/home/.bash_profile ~/.bash_profile
ln --force ~/desktop/system/profile/belimoth/home/.bashrc       ~/.bashrc
ln --force ~/desktop/system/profile/belimoth/home/.inputrc      ~/.inputrc
ln --force ~/desktop/system/profile/belimoth/home/.gitconfig    ~/.gitconfig

ln --force ~/desktop/system/profile/belimoth/vscode/keybindings.json ~/appdata/roaming/code/user/keybindings.json
ln --force ~/desktop/system/profile/belimoth/vscode/settings.json    ~/appdata/roaming/code/user/settings.json
